services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
            POSTGRES_USER: '${POSTGRES_USER}'
            POSTGRES_DB: '${POSTGRES_DB}'
            PGDATA: '/var/lib/postgresql/data/pgdata'

        volumes:
            - pg-data:/var/lib/postgresql/data/pgdata
        ports:
            - ${POSTGRES_PORT}:5432

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    pg-data:
