services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
            POSTGRES_USER: '${POSTGRES_USER}'
            POSTGRES_DB: '${POSTGRES_DB}'
            PGDATA: '/var/lib/postgresql/data/pgdata'

        volumes:
            - pg-data:/var/lib/postgresql/data/pgdata
        ports:
            - ${POSTGRES_PORT}:5432

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    dagster:
        build:
            context: ./dagster_app
        environment:
            DAGSTER_HOME: /app
        ports:
            - 3000:3000
        volumes:
            - dagster-storage:/app/storage
        depends_on:
            - db

volumes:
    pg-data:
    dagster-storage:
