# Generated by Django 5.2.6 on 2025-09-21 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apikey',
            new_name='api_apikey_key_5dc959_idx',
            old_name='api_key_key_idx',
        ),
    ]
