# Generated by Django 5.2.6 on 2025-09-20 00:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('global_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('data_source_id', models.AutoField(help_text='Primary key for the data source', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name for the data source', max_length=255)),
                ('type', models.CharField(choices=[('database', 'Database'), ('api', 'API'), ('file', 'File'), ('stream', 'Stream'), ('cloud', 'Cloud Storage'), ('other', 'Other')], help_text='Type of data source (database, API, file, etc.)', max_length=50)),
                ('connection_info', models.JSONField(help_text='Configuration and connection details for the data source')),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
