# Generated by Django 5.2.6 on 2025-09-21 06:02

import django.db.models.deletion
import pulling.models.alert
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulling', '0004_fieldstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alert',
            new_name='pulling_ale_data_so_c8f531_idx',
            old_name='pulling_alert_ds_status_idx',
        ),
        migrations.RenameIndex(
            model_name='alert',
            new_name='pulling_ale_severit_6f5400_idx',
            old_name='pulling_alert_severity_idx',
        ),
        migrations.AlterField(
            model_name='alert',
            name='data_source',
            field=models.ForeignKey(help_text='Data source this alert belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='pulling.datasource'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='details',
            field=models.JSONField(default=pulling.models.alert.default_details),
        ),
        migrations.AlterField(
            model_name='alert',
            name='field',
            field=models.ForeignKey(blank=True, help_text='Optional field this alert is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='pulling.fieldmetadata'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='table',
            field=models.ForeignKey(blank=True, help_text='Optional table this alert is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='pulling.tablemetadata'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Owner user of this data source', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldmetadata',
            name='global_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='fieldrelation',
            name='global_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tablemetadata',
            name='global_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
